spring:
  application:
    name: capi
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  jackson:
    parser:
      allow-comments: false
      allow-yaml-comments: false
    mapper:
      accept-case-insensitive-properties: false
    deserialization:
      fail-on-unknown-properties: true

server:
  max-http-header-size: 8KB
  tomcat:
    max-http-post-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 10ms,50ms,100ms,200ms,500ms,1s,2s,5s

logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"
  level:
    com.chesire.capi: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
