name: Pull Request CI

on:
  pull_request:
    branches: [ master ]

jobs:
  setup-cache:
    name: Gradle | Cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.gradle-cache.outputs.cache-hit }}
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: Java | Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle | Setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Gradle | Cache Dependencies
        id: gradle-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle | Download Dependencies
        run: ./gradlew dependencies --no-daemon

  static-analysis:
    name: Static Analysis | Code Quality
    runs-on: ubuntu-latest
    needs: setup-cache
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: Java | Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle | Setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Gradle | Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Ktlint | Code Style Check
        run: ./gradlew ktlintCheck --no-daemon --continue
          
      - name: SpotBugs | Bug Analysis
        run: ./gradlew spotbugsMain --no-daemon --continue
          
      - name: GitHub | Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: static-analysis-reports
          path: |
            build/reports/ktlint/
            build/reports/spotbugs/
          retention-days: 7

  test:
    name: Gradle | Test
    runs-on: ubuntu-latest
    needs: setup-cache
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: Java | Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle | Setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Gradle | Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle | Run Tests
        run: ./gradlew test --no-daemon --continue

      - name: GitHub | Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: build/reports/tests/test/
          retention-days: 7

  compile:
    name: Gradle | Build
    runs-on: ubuntu-latest
    needs: setup-cache
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: Java | Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle | Setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Gradle | Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle | Compile Application
        run: ./gradlew assemble --no-daemon

      - name: GitHub | Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/
          retention-days: 7